<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "webhelp"
 *
 * Auto generated by Extension Builder 2021-07-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'webcomponents viewhelper',
    'description' => 'Build simple Webcomponents like icalendar or vcard with viewhelpers',
    'category' => 'services',
    'author' => 'Dr. Dieter Porth',
    'author_email' => 'info@mobger.de',
    'state' => 'experimental',
    'clearCacheOnLoad' => 0,
    'version' => '10.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
