<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "webhelp"
 *
 * Auto generated by Extension Builder 2021-07-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'webcomponents examples',
    'description' => 'allows you to use simple web components like porthd-icalendar, porthd-vcard or porthd-listselect in your fluid-templates as viewhelper',
    'category' => 'services',
    'author' => 'Dr. Dieter Porth',
    'author_email' => 'info@mobger.de',
    'state' => 'experimental',
    'version' => '13.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-13.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
