<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "webhelp"
 *
 * Auto generated by Extension Builder 2021-07-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'web components als JS-viewhelper',
    'description' => 'Make your templates simpler and your frontend more dynamical with custom web components - generated by vibe-coding. ',
    'category' => 'frontend',
    'author' => 'Dr. Dieter Porth',
    'author_email' => 'info@mobger.de',
    'state' => 'experimental',
    'version' => '13.2.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-13.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
